# Generated by Django 4.0.4 on 2022-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_popularinfo_bvid_popularinfo_cid_popularinfo_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularinfo',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='popularinfo',
            name='replay',
        ),
        migrations.AddField(
            model_name='popularinfo',
            name='owner_mid',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='用户uid'),
        ),
        migrations.AddField(
            model_name='popularinfo',
            name='reply',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='aid',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='av号'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='bvid',
            field=models.CharField(blank=True, default='#', max_length=32, null=True, verbose_name='bv号'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='cid',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='弹幕id'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='coin',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='硬币数'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='ctime',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='danmu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='弹幕数'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='description',
            field=models.TextField(blank=True, default='#', null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='favourite',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='长度（秒数）'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='短链接'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='owner_face',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='owner_name',
            field=models.CharField(blank=True, default='没有昵称', max_length=64, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='picture',
            field=models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='视频封面'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='pubdate',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='reason',
            field=models.CharField(blank=True, default='#', max_length=64, null=True, verbose_name='推荐理由'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='share',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='分享数'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='tag_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='视频标签id'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='tag_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='视频标签'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='title',
            field=models.TextField(blank=True, default='标题', null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='type_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='视频分区id'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='type_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='视频分区'),
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='播放数'),
        ),
    ]
