# Generated by Django 4.0.4 on 2022-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_popularinfo_owner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_view', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='视频观看总数')),
                ('article_view', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='专栏观看总数')),
                ('birthday', models.CharField(blank=True, default='#', max_length=16, null=True, verbose_name='生日')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='视频总数')),
                ('face', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='用户头像')),
                ('follower', models.IntegerField(blank=True, default=0, null=True, verbose_name='粉丝数')),
                ('following', models.IntegerField(blank=True, default=0, null=True, verbose_name='关注数')),
                ('likes', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='获赞总数')),
                ('mid', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='用户uid')),
                ('name', models.CharField(blank=True, default='没有昵称', max_length=64, null=True, verbose_name='用户名')),
                ('sex', models.CharField(blank=True, default='保密', max_length=16, null=True, verbose_name='性别')),
                ('sign', models.TextField(blank=True, default='-', null=True, verbose_name='用户签名')),
            ],
        ),
        migrations.AlterField(
            model_name='popularinfo',
            name='coin',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='硬币数'),
        ),
    ]
