# Generated by Django 4.0.4 on 2022-05-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_peopleinfo_alter_popularinfo_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='av号')),
                ('bvid', models.CharField(blank=True, default='#', max_length=32, null=True, verbose_name='bv号')),
                ('cid', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='弹幕id')),
                ('coin', models.IntegerField(blank=True, default=1, null=True, verbose_name='硬币数')),
                ('ctime', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='发布时间')),
                ('danmu', models.IntegerField(blank=True, default=0, null=True, verbose_name='弹幕数')),
                ('description', models.TextField(blank=True, default='#', null=True, verbose_name='简介')),
                ('favourite', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('length', models.IntegerField(blank=True, default=0, null=True, verbose_name='长度（秒数）')),
                ('like', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('link', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='短链接')),
                ('owner_mid', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='用户uid')),
                ('picture', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='视频封面')),
                ('pubdate', models.BigIntegerField(blank=True, default=1, null=True, verbose_name='审核时间')),
                ('reply', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('share', models.IntegerField(blank=True, default=0, null=True, verbose_name='分享数')),
                ('tag_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='视频标签id')),
                ('tag_name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='视频标签')),
                ('title', models.TextField(blank=True, default='标题', null=True, verbose_name='标题')),
                ('type_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='视频分区id')),
                ('type_name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='视频分区')),
                ('view', models.IntegerField(blank=True, default=0, null=True, verbose_name='播放数')),
            ],
        ),
    ]
